- 👋 Hi, I’m @faridhassani95
- 👀 I’m interested in ...
- 🌱 I’m currently learning ...
- 💞️ I’m looking to collaborate on ...
- 📫 How to reach me ...
'
Farid = 'Hello i like to learning proogramming. i work for sukkara and do bussiness.'
<!---
faridhassani95/faridhassani95 is a ✨ special ✨ repository because its `README.md` (this file) appears on your GitHub profile.
You can click the Preview link to take a look at your changes.
--->
